### ISSUE TITLE
Localizations are not editable. Make them user resizable.

### ISSUE THREAD

**Issue by hohonuuli** [mbari-media-management/cthulhu#5] opened 2021-02-10 17:22 UTC
A bounding box can not be edited/resized in Cthulhu after it's initially drawn. A user should be able select them and resize them.

**Comment by carueda** [comment] 2021-03-30 02:28
@hohonuuli   I'm trying to see whether Cthulu can notify the removal of an annotation to VARS.  It's not clear to me yet if this is possible?. I have some basic functionality in place, initially with the approach of removing the existing annotation and then adding a new one once the user is happy with the redrawn box.  If this remove-then-add strategy is not feasible for some reason, then I would look into "updating" the existing annotation itself (again, if possible).

**Comment by carueda** [comment] 2021-03-30 02:46
Here's a screencast:  https://www.screencast.com/t/PA29j1pl

- added two boxes as usual
- typed 'E' to start editing the selected box (the 2nd one added)
- dragged one of corners  (red circles are used as handles for the resizing)
- upon mouse release, the modified box is added as intended, but the original box is still there (I'm not yet seeing a way to notify VARS about removals)
- similar steps on the 1st entered box.

**Comment by hohonuuli** [comment] 2021-03-30 15:39
> I'm trying to see whether Cthulhu can notify the removal of an annotation to VARS. It's not clear to me yet if this is possible?

@carueda Removing on the Cthulhu side should also remove the observation on the VARS side. But VARS is probably not be listening for the `remove` notification since Cthulhu didn't have edit capabilities. Probably the fastest way to evaluate that is to modify [Oryx](https://github.com/mbari-media-management/oryx) to listen for remove notifications. You can add that code [here](https://github.com/mbari-media-management/oryx/blob/main/src/main/java/org/mbari/App.java#L76)

You can use orxy as a sort of VARS simulator. It just listens for localization events from Cthuhlu.

**Comment by carueda** [comment] 2021-03-30 16:11
Thanks @hohonuuli 

 How to get access to the maven repo?  I'm getting a 401 when running `mvn clean javafx:run` --> `Authentication failed for https://maven.pkg.github.com/mbari-org/maven/org/mbari/vcr4j/vcr4j-sharktopoda-client/4.4.0.jre11/vcr4j-sharktopoda-client-4.4.0.jre11.pom 401 Unauthorized`

**Comment by hohonuuli** [comment] 2021-03-30 16:56
Github Packages is weird. You'll need to configure some authentication credentials. Docs for it are at <https://github.com/mbari-org/maven>

**Comment by hohonuuli** [comment] 2021-03-30 17:48
@carueda Sorry to keep directing you to Oryx, but it's probably the fastest way for you to tackle this at the moment. 

In Oryx, just add a selection listener to the table to listen for selected rows. There's a method on the IO object to add/remove the selected localizations.

> I think it would be good to allow the user to do selection on Cthulhu itself. 

You could add selection in Cthulhu too, but it's a hard requirement to allow the user to select the annotation in VARS.

**Comment by carueda** [comment] 2021-03-30 18:18
@hohonuuli  oryx can now send select notifications to cthulhu, thanks for the suggestion.  (btw, can you give me priv to push a branch with the mods to oryx?)   I'll continue the testing but it seems Cthulhu does not send removal notifications to the other side.

**Comment by hohonuuli** [comment] 2021-03-30 18:24
@carueda I've added you to Oryx. Cthulhu _should_ be pushing notifications; the library it's using is the exact same that VARS uses. Is the removal being propagated to it's IO observable list under the hood?

**Comment by carueda** [comment] 2021-03-30 18:57
Here's a cthulhu-oryx interaction screencast: https://www.screencast.com/t/JDopTlEKgr

This is oryx's log

```
Received: { [Localization{concept='Concept', elapsedTime=PT0.904S, localizationUuid=10ca7c4f-d45d-4d5a-87c5-35281b134d50}] added at 0 }
Localization{concept='Concept', elapsedTime=PT0.904S, localizationUuid=10ca7c4f-d45d-4d5a-87c5-35281b134d50}
Received: { [Localization{concept='Concept', elapsedTime=PT0.904S, localizationUuid=9179856c-7930-4850-85a1-aebbc63e2bff}] added at 0 }
Localization{concept='Concept', elapsedTime=PT0.904S, localizationUuid=9179856c-7930-4850-85a1-aebbc63e2bff}
Received: { [Localization{concept='Concept', elapsedTime=PT0.904S, localizationUuid=e1778a33-d58d-408c-a21f-15c79412cbdf}] added at 0 }
Localization{concept='Concept', elapsedTime=PT0.904S, localizationUuid=e1778a33-d58d-408c-a21f-15c79412cbdf}
newSelection: Localization{concept='Concept', elapsedTime=PT0.904S, localizationUuid=10ca7c4f-d45d-4d5a-87c5-35281b134d50}
newSelection: Localization{concept='Concept', elapsedTime=PT0.904S, localizationUuid=9179856c-7930-4850-85a1-aebbc63e2bff}
newSelection: Localization{concept='Concept', elapsedTime=PT0.904S, localizationUuid=e1778a33-d58d-408c-a21f-15c79412cbdf}
newSelection: Localization{concept='Concept', elapsedTime=PT0.904S, localizationUuid=10ca7c4f-d45d-4d5a-87c5-35281b134d50}
Received: { [Localization{concept='Concept', elapsedTime=PT-0.001S, localizationUuid=8a3eb8a2-848a-4a63-9d4e-accb859a730b}] added at 0 }
Localization{concept='Concept', elapsedTime=PT-0.001S, localizationUuid=8a3eb8a2-848a-4a63-9d4e-accb859a730b}
```

that is, not showing any "removal" requests from Cthulhu.

Again, upon the just completed box resizing, Cthulhu is supposed to be sending a `remove` event with the associated UUID and then do the usual `newAnnotation` to trigger the addition of the updated box.  That second part works, but the removal part does not.  It think it's just that the `remove` call I'm doing is only intended to reflect a request for removal from the other side, not to do a request for removal originating from Cthulhu.  Make sense?   I'll try to (again) follow the logic for newAnnotation and see if there's actually something similar for removal; if not, of course we will have to add that as well.

**Comment by carueda** [comment] 2021-04-02 17:24
resolved per merged https://github.com/mbari-media-management/cthulhu/pull/9

**Closed by carueda** 2021-04-02 17:24 UTC
